### ISSUE TITLE
JsonGrid Visual: Too many value issue

### ISSUE THREAD

**Issue by prateekraina** [maqsoftware/PowerBI-visuals#253]
Hi,

What is the limit of data points for this visual.
Can it handle 1 lakh rows?

Prateek Raina

**Comment by maqprachimishra** [comment]
Hello Prateek,
Custom Visuals can support maximum of 30,000 rows. R visuals can support upto 150,000 rows.
You can refer to the documentation [here](https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/DataViewMappings.md#data-reduction-algorithm)

Thanks,
Prachi Mishra
MAQ Software
