### ISSUE TITLE
Linear Gauge - Target Value Not Aligning Properly

### ISSUE THREAD

**Issue by biYogi** [maqsoftware/PowerBI-visuals#32]
Hello,

I love the linear gauge. Thanks for creating it. I'm seeing an issue where the numeric Target Value doesn't align to the Line value of the Target Value. No matter how I size the visual, it won't align. Is there a way to fix this?
![linear-delete](https://cloud.githubusercontent.com/assets/25780348/22952100/7df6868c-f2c0-11e6-9831-7349f183ec76.JPG)

Thanks for looking into this!

**Comment by KeshavPolepalle** [comment]
Hey biYogi,

Thanks for your feedback. Our dev team is working on a fix. We will be able to get it fixed in next couple of days. 

Thanks
Keshav

**Comment by KeshavPolepalle** [comment]
We have fixed the issue. Visual is located here https://github.com/maqsoftware/PowerBI-visuals/tree/master/src/Clients/CustomVisuals/visuals/lineargauge/
