### ISSUE TITLE
Grid Visual: API Redirection not working

### ISSUE THREAD

**Issue by prateekraina** [maqsoftware/PowerBI-visuals#36]
I have downloaded the sample pbix and published it on my workspace. When i click on the CustomerID value for which custom redirection is On, it does not redirect.

**Comment by KeshavPolepalle** [comment]
@prateekraina we are looking into this.

**Comment by RicardoCousins** [comment]
@prateekraina Thanks for reaching out to us. We tried reproducing the mentioned issue but could not do the same. For further understanding API redirection, please read the ‘API calling with Power BI Grid visual’ document attached.
[API_calling_with_Power_BI_Grid_visual.docx](https://github.com/maqsoftware/PowerBI-visuals/files/1409048/API_calling_with_Power_BI_Grid_visual.docx)
