### ISSUE TITLE
Issue with date time of the calender 

### ISSUE THREAD

**Issue by bramvbi** [maqsoftware/PowerBI-visuals#362]
![image](https://user-images.githubusercontent.com/48127623/53965274-28f5bc80-40f1-11e9-8948-aa83d8b251e7.png)

We have an issue where the datetime does not correspond with the time in the visual. 
As you can see in the attached screenshot, is the startdatetime of the blue activity 09:45 and the enddatetime 10:45 

However the tooltips show different values (endtime = T08:45:00:000:Z .  and the timeline of the visual show the blue event between 07:45 and 8:45.

It might be related to the timeoffset that we are on here (+1/+2 Amsterdam time )

Im I doing something wrong here or is it relaed to the visual itself?

**Comment by maqprachimishra** [comment]
Hello @bramvbi ,

We have updated Calendar by MAQ Software to v3.0.3 with bug fixes.
 
It generally takes 2-3 weeks for the changes to reflect on App source.
We recommend you to download the visual after 2-3 weeks and let us know your feedback.

Thanks,
Prachi Mishra
MAQ Software

**Comment by bramvbi** [comment]
Hi Prachi,

Thanks for the reply. I just downloaded the version from Github  (assuming that this is the latest version, it says 3.03) 
That did not solve the issue. Do not know whether my assumption that github contains version v3.03 is incorrect or whether the issue is not part of the bug fixes.

**Comment by maqprachimishra** [comment]
Hello @bramvbi ,

The GitHub repository does contain the latest source code but the GUID of the .pbiviz package file is linked to the visual published on App source. Hence, any package you import with the same GUID will reflect the build published on App source.

Thanks,
Prachi Mishra
MAQ Software

**Comment by bramvbi** [comment]
HI @maqprachimishra 

Thanks again! I will be waiting then:)

**Comment by bramvbi** [comment]
Just downloaded the new version and the times are correct now. Thanks!
