### ISSUE TITLE
Date Time Format

### ISSUE THREAD

**Issue by tnolan1688** [maqsoftware/PowerBI-visuals#38]
Allow for standard date/time formats instead of lengthy GMT date time

**Comment by MeghaDesai** [comment]
Thanks for reaching out Thomas. We have added this feature in our backlog and will notify once it is rolled out.

**Comment by RicardoCousins** [comment]
Hi Thomas,

We have released an updated version of this visual to Microsoft AppSource in response to your request. The update will be available in a couple of weeks at AppSource:
https://appsource.microsoft.com/product/office/wa104380825

Please keep sending your awesome feedback.
