### ISSUE TITLE
Linear gauge by MAQ Software is blank when power bi report is exported to powerpoint file

### ISSUE THREAD

**Issue by Tzouros** [maqsoftware/PowerBI-visuals#434]
Hello, all of a sudden when exporting my Power BI report to a powerpoint or pdf file the linear gauge visuals remain blank. This happens when the report is exported using Power BI Service. When I export the report using Power BI Desktop (to a pdf file, I don't have the option for a powerpoint file) the gauge visuals are fine. The gauges are displayed fine both in Power BI Service and in the mobile application. The issue appeared suddenly, until last month the gauges were displayed fine when exported to powerpoint or pdf files.
Power BI Visual ID: LinearGauge1450736844786, version 3.5.3  
[P&L and Opex per Segment (2).pptx](https://github.com/maqsoftware/PowerBI-visuals/files/3977656/P.L.and.Opex.per.Segment.2.pptx)
![Report with gauges](https://user-images.githubusercontent.com/59012537/71074751-7d9f8b00-218b-11ea-8e8d-afad756a1fdd.png)

**Comment by NainakshiB** [comment]
Hello,

It was a known issue listed in [Support](https://powerbi.microsoft.com/en-us/support/)
 
![image](https://user-images.githubusercontent.com/48585913/71474495-b8e03080-2801-11ea-94ac-da040f2633f4.png)


Please try to export the report again using PowerPoint/PDF and let us know if it works for you now.

Thanks,
Nainakshi Batra
MAQ Software

**Comment by Tzouros** [comment]
Thank you for your reply, I confirm it works fine since 20/12/2019.
